(setq mew-config-alist
        '(("default"
           ("proto" . "%")
           ("name" . "XXX")
           ("user" . "XXX")
           ("mail-domain" . "kwansei.ac.jp")
           ("smtp-user" . "XXX@nuc.kwansei.ac.jp")
           ("smtp-server" . "smtp.office365.com")
           ("smtp-auth" . t)
           ("smtp-ssl-port" . "587")
           ("smtp-port" . "587")
           ("smtp-ssl" . t)
           ("imap-server" . "outlook.office365.com")
           ("imap-user" . "XXX@nuc.kwansei.ac.jp")
           ("imap-ssl" . t)
           ("imap-port" . "143")
           ("imap-delete" . "nil")
           )))
